### ISSUE TITLE
Use of UI5 modules instead of globals

### ISSUE THREAD

**Issue by tobiasso85** [vobu/ui5-codecompletion#7]
with 1.58 of UI5 modules are used instead of globals.

E.g.
Before
```js
jQuery.sap.log.info("text");
```

After
```js
sap.ui.define(["sap/base/Log"],  function(Log) {
Log.info("text");
});
```

Would it be possible to include this as well.

@see https://sapui5.hana.ondemand.com/#/topic/a075ed88ef324261bca41813a6ac4a1c.html

**Comment by vobu** [comment]
Hi,

the UI5 source modules are picked up by default - so if you'd be doing in your WebStorm Project folder:
~~~bash
$> ui5-codecompletion install \
       --from=https://openui5.hana.ondemand.com/downloads/openui5-runtime-1.61.2.zip

downloading https://openui5.hana.ondemand.com/downloads/openui5-runtime-1.61.2.zip
   [====================] 1744049/bps 100% 0.0s
extracting UI5 sources to /Users/vbuzek/_tmp/node-test/.ui5...
   ...done!
deleting .zip: done!
providing code completion from 
   .ui5/resources 
for 2379 files (*dbg.js only).
~~~
...the improved UI5 modules should be recognized and available as `LocalUI5Library` in the Scopes setting.
And yes, I have to update the documentation (README.md) of this repo; kinda outdated.

HTH?

Best, V.
